/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedAdminUnitsIndexRouteImport } from './routes/_authenticated/admin/units/index'
import { Route as AuthenticatedAdminTemplatesIndexRouteImport } from './routes/_authenticated/admin/templates/index'
import { Route as AuthenticatedAdminBuildingsIndexRouteImport } from './routes/_authenticated/admin/buildings/index'
import { Route as AuthenticatedAdminUsersUserIdRouteImport } from './routes/_authenticated/admin/users/$userId'
import { Route as AuthenticatedAdminTemplatesTemplateIdRouteImport } from './routes/_authenticated/admin/templates/$templateId'
import { Route as AuthenticatedAdminBuildingsBuildingIdRouteImport } from './routes/_authenticated/admin/buildings/$buildingId'
import { Route as AuthenticatedAdminUnitsUnitIdIndexRouteImport } from './routes/_authenticated/admin/units/$unitId/index'
import { Route as AuthenticatedAdminFinancialsPaymentsIndexRouteImport } from './routes/_authenticated/admin/financials/payments/index'
import { Route as AuthenticatedAdminFinancialsInvoicesIndexRouteImport } from './routes/_authenticated/admin/financials/invoices/index'
import { Route as AuthenticatedAdminFinancialsFeesIndexRouteImport } from './routes/_authenticated/admin/financials/fees/index'
import { Route as AuthenticatedAdminFinancialsPaymentsPaymentIdRouteImport } from './routes/_authenticated/admin/financials/payments/$paymentId'
import { Route as AuthenticatedAdminFinancialsInvoicesInvoiceIdRouteImport } from './routes/_authenticated/admin/financials/invoices/$invoiceId'
import { Route as AuthenticatedAdminFinancialsFeesFeeIdRouteImport } from './routes/_authenticated/admin/financials/fees/$feeId'
import { Route as AuthenticatedAdminUnitsUnitIdLeasesIndexRouteImport } from './routes/_authenticated/admin/units/$unitId/leases/index'
import { Route as AuthenticatedAdminUnitsUnitIdLeasesLeaseIdIndexRouteImport } from './routes/_authenticated/admin/units/$unitId/leases/$leaseId/index'

const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_authenticated/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUnitsIndexRoute =
  AuthenticatedAdminUnitsIndexRouteImport.update({
    id: '/units/',
    path: '/units/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTemplatesIndexRoute =
  AuthenticatedAdminTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBuildingsIndexRoute =
  AuthenticatedAdminBuildingsIndexRouteImport.update({
    id: '/buildings/',
    path: '/buildings/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersUserIdRoute =
  AuthenticatedAdminUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTemplatesTemplateIdRoute =
  AuthenticatedAdminTemplatesTemplateIdRouteImport.update({
    id: '/templates/$templateId',
    path: '/templates/$templateId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBuildingsBuildingIdRoute =
  AuthenticatedAdminBuildingsBuildingIdRouteImport.update({
    id: '/buildings/$buildingId',
    path: '/buildings/$buildingId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUnitsUnitIdIndexRoute =
  AuthenticatedAdminUnitsUnitIdIndexRouteImport.update({
    id: '/units/$unitId/',
    path: '/units/$unitId/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFinancialsPaymentsIndexRoute =
  AuthenticatedAdminFinancialsPaymentsIndexRouteImport.update({
    id: '/financials/payments/',
    path: '/financials/payments/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFinancialsInvoicesIndexRoute =
  AuthenticatedAdminFinancialsInvoicesIndexRouteImport.update({
    id: '/financials/invoices/',
    path: '/financials/invoices/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFinancialsFeesIndexRoute =
  AuthenticatedAdminFinancialsFeesIndexRouteImport.update({
    id: '/financials/fees/',
    path: '/financials/fees/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFinancialsPaymentsPaymentIdRoute =
  AuthenticatedAdminFinancialsPaymentsPaymentIdRouteImport.update({
    id: '/financials/payments/$paymentId',
    path: '/financials/payments/$paymentId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFinancialsInvoicesInvoiceIdRoute =
  AuthenticatedAdminFinancialsInvoicesInvoiceIdRouteImport.update({
    id: '/financials/invoices/$invoiceId',
    path: '/financials/invoices/$invoiceId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFinancialsFeesFeeIdRoute =
  AuthenticatedAdminFinancialsFeesFeeIdRouteImport.update({
    id: '/financials/fees/$feeId',
    path: '/financials/fees/$feeId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUnitsUnitIdLeasesIndexRoute =
  AuthenticatedAdminUnitsUnitIdLeasesIndexRouteImport.update({
    id: '/units/$unitId/leases/',
    path: '/units/$unitId/leases/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUnitsUnitIdLeasesLeaseIdIndexRoute =
  AuthenticatedAdminUnitsUnitIdLeasesLeaseIdIndexRouteImport.update({
    id: '/units/$unitId/leases/$leaseId/',
    path: '/units/$unitId/leases/$leaseId/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/buildings/$buildingId': typeof AuthenticatedAdminBuildingsBuildingIdRoute
  '/admin/templates/$templateId': typeof AuthenticatedAdminTemplatesTemplateIdRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/admin/buildings': typeof AuthenticatedAdminBuildingsIndexRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesIndexRoute
  '/admin/units': typeof AuthenticatedAdminUnitsIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/admin/financials/fees/$feeId': typeof AuthenticatedAdminFinancialsFeesFeeIdRoute
  '/admin/financials/invoices/$invoiceId': typeof AuthenticatedAdminFinancialsInvoicesInvoiceIdRoute
  '/admin/financials/payments/$paymentId': typeof AuthenticatedAdminFinancialsPaymentsPaymentIdRoute
  '/admin/financials/fees': typeof AuthenticatedAdminFinancialsFeesIndexRoute
  '/admin/financials/invoices': typeof AuthenticatedAdminFinancialsInvoicesIndexRoute
  '/admin/financials/payments': typeof AuthenticatedAdminFinancialsPaymentsIndexRoute
  '/admin/units/$unitId': typeof AuthenticatedAdminUnitsUnitIdIndexRoute
  '/admin/units/$unitId/leases': typeof AuthenticatedAdminUnitsUnitIdLeasesIndexRoute
  '/admin/units/$unitId/leases/$leaseId': typeof AuthenticatedAdminUnitsUnitIdLeasesLeaseIdIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/buildings/$buildingId': typeof AuthenticatedAdminBuildingsBuildingIdRoute
  '/admin/templates/$templateId': typeof AuthenticatedAdminTemplatesTemplateIdRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/admin/buildings': typeof AuthenticatedAdminBuildingsIndexRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesIndexRoute
  '/admin/units': typeof AuthenticatedAdminUnitsIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/admin/financials/fees/$feeId': typeof AuthenticatedAdminFinancialsFeesFeeIdRoute
  '/admin/financials/invoices/$invoiceId': typeof AuthenticatedAdminFinancialsInvoicesInvoiceIdRoute
  '/admin/financials/payments/$paymentId': typeof AuthenticatedAdminFinancialsPaymentsPaymentIdRoute
  '/admin/financials/fees': typeof AuthenticatedAdminFinancialsFeesIndexRoute
  '/admin/financials/invoices': typeof AuthenticatedAdminFinancialsInvoicesIndexRoute
  '/admin/financials/payments': typeof AuthenticatedAdminFinancialsPaymentsIndexRoute
  '/admin/units/$unitId': typeof AuthenticatedAdminUnitsUnitIdIndexRoute
  '/admin/units/$unitId/leases': typeof AuthenticatedAdminUnitsUnitIdLeasesIndexRoute
  '/admin/units/$unitId/leases/$leaseId': typeof AuthenticatedAdminUnitsUnitIdLeasesLeaseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/buildings/$buildingId': typeof AuthenticatedAdminBuildingsBuildingIdRoute
  '/_authenticated/admin/templates/$templateId': typeof AuthenticatedAdminTemplatesTemplateIdRoute
  '/_authenticated/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/_authenticated/admin/buildings/': typeof AuthenticatedAdminBuildingsIndexRoute
  '/_authenticated/admin/templates/': typeof AuthenticatedAdminTemplatesIndexRoute
  '/_authenticated/admin/units/': typeof AuthenticatedAdminUnitsIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/admin/financials/fees/$feeId': typeof AuthenticatedAdminFinancialsFeesFeeIdRoute
  '/_authenticated/admin/financials/invoices/$invoiceId': typeof AuthenticatedAdminFinancialsInvoicesInvoiceIdRoute
  '/_authenticated/admin/financials/payments/$paymentId': typeof AuthenticatedAdminFinancialsPaymentsPaymentIdRoute
  '/_authenticated/admin/financials/fees/': typeof AuthenticatedAdminFinancialsFeesIndexRoute
  '/_authenticated/admin/financials/invoices/': typeof AuthenticatedAdminFinancialsInvoicesIndexRoute
  '/_authenticated/admin/financials/payments/': typeof AuthenticatedAdminFinancialsPaymentsIndexRoute
  '/_authenticated/admin/units/$unitId/': typeof AuthenticatedAdminUnitsUnitIdIndexRoute
  '/_authenticated/admin/units/$unitId/leases/': typeof AuthenticatedAdminUnitsUnitIdLeasesIndexRoute
  '/_authenticated/admin/units/$unitId/leases/$leaseId/': typeof AuthenticatedAdminUnitsUnitIdLeasesLeaseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/admin/'
    | '/admin/buildings/$buildingId'
    | '/admin/templates/$templateId'
    | '/admin/users/$userId'
    | '/admin/buildings'
    | '/admin/templates'
    | '/admin/units'
    | '/admin/users'
    | '/admin/financials/fees/$feeId'
    | '/admin/financials/invoices/$invoiceId'
    | '/admin/financials/payments/$paymentId'
    | '/admin/financials/fees'
    | '/admin/financials/invoices'
    | '/admin/financials/payments'
    | '/admin/units/$unitId'
    | '/admin/units/$unitId/leases'
    | '/admin/units/$unitId/leases/$leaseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/admin'
    | '/admin/buildings/$buildingId'
    | '/admin/templates/$templateId'
    | '/admin/users/$userId'
    | '/admin/buildings'
    | '/admin/templates'
    | '/admin/units'
    | '/admin/users'
    | '/admin/financials/fees/$feeId'
    | '/admin/financials/invoices/$invoiceId'
    | '/admin/financials/payments/$paymentId'
    | '/admin/financials/fees'
    | '/admin/financials/invoices'
    | '/admin/financials/payments'
    | '/admin/units/$unitId'
    | '/admin/units/$unitId/leases'
    | '/admin/units/$unitId/leases/$leaseId'
  id:
    | '__root__'
    | '/_authenticated/admin'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/buildings/$buildingId'
    | '/_authenticated/admin/templates/$templateId'
    | '/_authenticated/admin/users/$userId'
    | '/_authenticated/admin/buildings/'
    | '/_authenticated/admin/templates/'
    | '/_authenticated/admin/units/'
    | '/_authenticated/admin/users/'
    | '/_authenticated/admin/financials/fees/$feeId'
    | '/_authenticated/admin/financials/invoices/$invoiceId'
    | '/_authenticated/admin/financials/payments/$paymentId'
    | '/_authenticated/admin/financials/fees/'
    | '/_authenticated/admin/financials/invoices/'
    | '/_authenticated/admin/financials/payments/'
    | '/_authenticated/admin/units/$unitId/'
    | '/_authenticated/admin/units/$unitId/leases/'
    | '/_authenticated/admin/units/$unitId/leases/$leaseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/units/': {
      id: '/_authenticated/admin/units/'
      path: '/units'
      fullPath: '/admin/units'
      preLoaderRoute: typeof AuthenticatedAdminUnitsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/templates/': {
      id: '/_authenticated/admin/templates/'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/buildings/': {
      id: '/_authenticated/admin/buildings/'
      path: '/buildings'
      fullPath: '/admin/buildings'
      preLoaderRoute: typeof AuthenticatedAdminBuildingsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users/$userId': {
      id: '/_authenticated/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/templates/$templateId': {
      id: '/_authenticated/admin/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/admin/templates/$templateId'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesTemplateIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/buildings/$buildingId': {
      id: '/_authenticated/admin/buildings/$buildingId'
      path: '/buildings/$buildingId'
      fullPath: '/admin/buildings/$buildingId'
      preLoaderRoute: typeof AuthenticatedAdminBuildingsBuildingIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/units/$unitId/': {
      id: '/_authenticated/admin/units/$unitId/'
      path: '/units/$unitId'
      fullPath: '/admin/units/$unitId'
      preLoaderRoute: typeof AuthenticatedAdminUnitsUnitIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/financials/payments/': {
      id: '/_authenticated/admin/financials/payments/'
      path: '/financials/payments'
      fullPath: '/admin/financials/payments'
      preLoaderRoute: typeof AuthenticatedAdminFinancialsPaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/financials/invoices/': {
      id: '/_authenticated/admin/financials/invoices/'
      path: '/financials/invoices'
      fullPath: '/admin/financials/invoices'
      preLoaderRoute: typeof AuthenticatedAdminFinancialsInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/financials/fees/': {
      id: '/_authenticated/admin/financials/fees/'
      path: '/financials/fees'
      fullPath: '/admin/financials/fees'
      preLoaderRoute: typeof AuthenticatedAdminFinancialsFeesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/financials/payments/$paymentId': {
      id: '/_authenticated/admin/financials/payments/$paymentId'
      path: '/financials/payments/$paymentId'
      fullPath: '/admin/financials/payments/$paymentId'
      preLoaderRoute: typeof AuthenticatedAdminFinancialsPaymentsPaymentIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/financials/invoices/$invoiceId': {
      id: '/_authenticated/admin/financials/invoices/$invoiceId'
      path: '/financials/invoices/$invoiceId'
      fullPath: '/admin/financials/invoices/$invoiceId'
      preLoaderRoute: typeof AuthenticatedAdminFinancialsInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/financials/fees/$feeId': {
      id: '/_authenticated/admin/financials/fees/$feeId'
      path: '/financials/fees/$feeId'
      fullPath: '/admin/financials/fees/$feeId'
      preLoaderRoute: typeof AuthenticatedAdminFinancialsFeesFeeIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/units/$unitId/leases/': {
      id: '/_authenticated/admin/units/$unitId/leases/'
      path: '/units/$unitId/leases'
      fullPath: '/admin/units/$unitId/leases'
      preLoaderRoute: typeof AuthenticatedAdminUnitsUnitIdLeasesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/units/$unitId/leases/$leaseId/': {
      id: '/_authenticated/admin/units/$unitId/leases/$leaseId/'
      path: '/units/$unitId/leases/$leaseId'
      fullPath: '/admin/units/$unitId/leases/$leaseId'
      preLoaderRoute: typeof AuthenticatedAdminUnitsUnitIdLeasesLeaseIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminBuildingsBuildingIdRoute: typeof AuthenticatedAdminBuildingsBuildingIdRoute
  AuthenticatedAdminTemplatesTemplateIdRoute: typeof AuthenticatedAdminTemplatesTemplateIdRoute
  AuthenticatedAdminUsersUserIdRoute: typeof AuthenticatedAdminUsersUserIdRoute
  AuthenticatedAdminBuildingsIndexRoute: typeof AuthenticatedAdminBuildingsIndexRoute
  AuthenticatedAdminTemplatesIndexRoute: typeof AuthenticatedAdminTemplatesIndexRoute
  AuthenticatedAdminUnitsIndexRoute: typeof AuthenticatedAdminUnitsIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
  AuthenticatedAdminFinancialsFeesFeeIdRoute: typeof AuthenticatedAdminFinancialsFeesFeeIdRoute
  AuthenticatedAdminFinancialsInvoicesInvoiceIdRoute: typeof AuthenticatedAdminFinancialsInvoicesInvoiceIdRoute
  AuthenticatedAdminFinancialsPaymentsPaymentIdRoute: typeof AuthenticatedAdminFinancialsPaymentsPaymentIdRoute
  AuthenticatedAdminFinancialsFeesIndexRoute: typeof AuthenticatedAdminFinancialsFeesIndexRoute
  AuthenticatedAdminFinancialsInvoicesIndexRoute: typeof AuthenticatedAdminFinancialsInvoicesIndexRoute
  AuthenticatedAdminFinancialsPaymentsIndexRoute: typeof AuthenticatedAdminFinancialsPaymentsIndexRoute
  AuthenticatedAdminUnitsUnitIdIndexRoute: typeof AuthenticatedAdminUnitsUnitIdIndexRoute
  AuthenticatedAdminUnitsUnitIdLeasesIndexRoute: typeof AuthenticatedAdminUnitsUnitIdLeasesIndexRoute
  AuthenticatedAdminUnitsUnitIdLeasesLeaseIdIndexRoute: typeof AuthenticatedAdminUnitsUnitIdLeasesLeaseIdIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminBuildingsBuildingIdRoute:
      AuthenticatedAdminBuildingsBuildingIdRoute,
    AuthenticatedAdminTemplatesTemplateIdRoute:
      AuthenticatedAdminTemplatesTemplateIdRoute,
    AuthenticatedAdminUsersUserIdRoute: AuthenticatedAdminUsersUserIdRoute,
    AuthenticatedAdminBuildingsIndexRoute:
      AuthenticatedAdminBuildingsIndexRoute,
    AuthenticatedAdminTemplatesIndexRoute:
      AuthenticatedAdminTemplatesIndexRoute,
    AuthenticatedAdminUnitsIndexRoute: AuthenticatedAdminUnitsIndexRoute,
    AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
    AuthenticatedAdminFinancialsFeesFeeIdRoute:
      AuthenticatedAdminFinancialsFeesFeeIdRoute,
    AuthenticatedAdminFinancialsInvoicesInvoiceIdRoute:
      AuthenticatedAdminFinancialsInvoicesInvoiceIdRoute,
    AuthenticatedAdminFinancialsPaymentsPaymentIdRoute:
      AuthenticatedAdminFinancialsPaymentsPaymentIdRoute,
    AuthenticatedAdminFinancialsFeesIndexRoute:
      AuthenticatedAdminFinancialsFeesIndexRoute,
    AuthenticatedAdminFinancialsInvoicesIndexRoute:
      AuthenticatedAdminFinancialsInvoicesIndexRoute,
    AuthenticatedAdminFinancialsPaymentsIndexRoute:
      AuthenticatedAdminFinancialsPaymentsIndexRoute,
    AuthenticatedAdminUnitsUnitIdIndexRoute:
      AuthenticatedAdminUnitsUnitIdIndexRoute,
    AuthenticatedAdminUnitsUnitIdLeasesIndexRoute:
      AuthenticatedAdminUnitsUnitIdLeasesIndexRoute,
    AuthenticatedAdminUnitsUnitIdLeasesLeaseIdIndexRoute:
      AuthenticatedAdminUnitsUnitIdLeasesLeaseIdIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
